# Generated by Django 3.2.18 on 2023-04-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_termino', models.DateTimeField()),
                ('carga_horario', models.IntegerField()),
                ('logo', models.ImageField(upload_to='logos')),
                ('cor_principal', models.CharField(max_length=7)),
                ('cor_segundaria', models.CharField(max_length=7)),
                ('cor_fundo', models.CharField(max_length=7)),
            ],
        ),
    ]
