# Generated by Django 3.2.18 on 2023-04-12 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_criador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='carga_horario',
            new_name='carga_horaria',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='cor_segundaria',
            new_name='cor_secundaria',
        ),
    ]
