# Generated by Django 3.2.18 on 2023-04-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='participantes',
        ),
    ]
